<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::table('collections', function (Blueprint $table) {

            /*
             * BUSY Voucher Code.
             *
             * This stores the unique voucher code generated by BUSY.
             * It is used later for SC=4 modification.
             */
            $table->string('busycollection_id')
                ->nullable()
                ->index()
                ->change();

            /*
             * BUSY Voucher Number.
             *
             * This is useful for display/reference.
             */
            $table->string('busy_voucher_no')
                ->nullable()
                ->after('busycollection_id');

            /*
             * BUSY Voucher Series.
             */
            $table->string('busy_voucher_series')
                ->nullable()
                ->after('busy_voucher_no');

            /*
             * BUSY synchronization state.
             */
            $table->string('busy_sync_status')
                ->default('pending')
                ->after('busy_voucher_series');

            /*
             * Last BUSY sync response/error.
             */
            $table->text('busy_sync_message')
                ->nullable()
                ->after('busy_sync_status');

            /*
             * Last successful BUSY synchronization time.
             */
            $table->timestamp('busy_synced_at')
                ->nullable()
                ->after('busy_sync_message');

            $table->index(
                ['company_id', 'busycollection_id'],
                'collections_company_busycollection_index'
            );
        });
    }

    public function down(): void
    {
        Schema::table('collections', function (Blueprint $table) {

            $table->dropIndex(
                'collections_company_busycollection_index'
            );

            $table->dropColumn([
                'busy_voucher_no',
                'busy_voucher_series',
                'busy_sync_status',
                'busy_sync_message',
                'busy_synced_at',
            ]);
        });
    }
};